### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by yuritoledo**
Updated readme and added some link.

### CODE REVIEW

**Comment by CharlesStover** [comment]
Thank you for the `reactn`->`react` correction.

The hooks work in 16.7 alpha, so it doesn't actually have to be 16.8.

Is there a reason you stated 16.8.1 instead of 16.8? Is there a bug in 16.8.0 that prevents hooks from working?

**Comment by drebits** [comment]
Hi @CharlesStover. When will you change to the most recent stable react version (16.8.1)? In my team we need that version.

**Comment by CharlesStover** [comment]
@drebits ReactN should already support 16.8.1. It is intended to support all versions of React. If you are encountering an error with 16.8.1, please open an Issue for it, and I'll resolve it immediately!

**Comment by yuritoledo** [comment]
Fixed, my bad!
Look at that: https://reactjs.org/blog/2019/02/06/react-v16.8.0.html

**Comment by CharlesStover** [comment]
Thanks for the PR! I appreciate the community involvement.

**Pull request merged**
