### PR TITLE
Update for React 18.2

### PR DESCRIPTION
**Pull request by gtryus**
- React 18.2 double renders in dev mode so tests were adjusted

### CODE REVIEW

**Comment by gtryus** [comment]
Yeah, when I tried compiling with the latest version of react-scripts (5.0.1) which uses web pack 5 (without node) instead of web pack 4, the program complained that he version of reactn wouldn't work with it and now that I have updated it, it works. I included a compiled copy in the repo but I could use the standard one if it was upgraded. On the other hand, upgrading it might break everyone trying to use it with React 16...

**Comment by CharlesStover** [comment]
That's interesting. You only updated the dev dependencies, which shouldn't have affected the build at all. Can you share the error you are getting?

**Comment by gtryus** [comment]
I may actually have figured out how to solve this error when I did the
upgrade but there is the error I am seeing now:

Uncaught TypeError TypeError: use_force_update_1.default is not a function
    at _useGlobal
(c:\Users\Trihus\git\transcriber\node_modules\reactn\build\use-global.js:16:1)
    at TokenProvider
(c:\Users\Trihus\git\transcriber\src\context\TokenProvider.tsx:57:1)
    at renderWithHooks
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:16305:1)
    at mountIndeterminateComponent
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:20074:1)
    at beginWork
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:21587:1)
    at callCallback
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:4164:1)
    at invokeGuardedCallbackDev
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:4213:1)
    at invokeGuardedCallback
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:4277:1)
    at beginWork$1
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:27451:1)
    at performUnitOfWork
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:26557:1)
    at workLoopSync
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:26466:1)
    at renderRootSync
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:26434:1)
    at performSyncWorkOnRoot
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:26085:1)
    at flushSyncCallbacks
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:12042:1)
    at flushSync
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:26201:1)
    at legacyCreateRootFromDOMContainer
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:29575:1)
    at legacyRenderSubtreeIntoContainer
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:29601:1)
    at render
(c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:29685:1)
    at <anonymous> (c:\Users\Trihus\git\transcriber\src\index.tsx:224:1)
    --- Promise.then ---
    at ./src/index.tsx (c:\Users\Trihus\git\transcriber\src\index.tsx:184:1)
    at options.factory
(c:\Users\Trihus\git\transcriber\webpack\runtime\react refresh:6:1)
    at __webpack_require__
(c:\Users\Trihus\git\transcriber\webpack\bootstrap:24:1)
    at <anonymous> (c:\Users\Trihus\git\transcriber\webpack\startup:7:1)
    at <anonymous> (localhost꞉3000/static/js/bundle.js:462027:12)
_useGlobal @
c:\Users\Trihus\git\transcriber\node_modules\reactn\build\use-global.js:16
TokenProvider @
c:\Users\Trihus\git\transcriber\src\context\TokenProvider.tsx:57
renderWithHooks @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:16305
mountIndeterminateComponent @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:20074
beginWork @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:21587
callCallback @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:4164
invokeGuardedCallbackDev @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:4213
invokeGuardedCallback @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:4277
beginWork$1 @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:27451
performUnitOfWork @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:26557
workLoopSync @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:26466
renderRootSync @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:26434
performSyncWorkOnRoot @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:26085
flushSyncCallbacks @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:12042
flushSync @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:26201
legacyCreateRootFromDOMContainer @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:29575
legacyRenderSubtreeIntoContainer @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:29601
render @
c:\Users\Trihus\git\transcriber\node_modules\react-dom\cjs\react-dom.development.js:29685
<anonymous> @ c:\Users\Trihus\git\transcriber\src\index.tsx:224
◀ Promise.then ▶
./src/index.tsx @ c:\Users\Trihus\git\transcriber\src\index.tsx:184
options.factory @ c:\Users\Trihus\git\transcriber\webpack\runtime\react
refresh:6
__webpack_require__ @ c:\Users\Trihus\git\transcriber\webpack\bootstrap:24
<anonymous> @ c:\Users\Trihus\git\transcriber\webpack\startup:7
<anonymous> @ localhost꞉3000/static/js/bundle.js:462027:12
The above error occurred in the <TokenProvider> component:

    at TokenProvider (http://localhost:3000/static/js/bundle.js:50717:5)
    at TokenChecked
    at Auth0Provider (http://localhost:3000/static/js/bundle.js:97512:23)
    at AuthApp
    at ProxyFacade (http://localhost:3000/static/js/bundle.js:355758:20)
    at DataProvider (http://localhost:3000/static/js/bundle.js:412269:5)
    at DataProvider
    at Root

Greg Trihus

**Comment by gtryus** [comment]
Yes, I was able to get it to work by adding:

"use-force-update": "1.0.5",

to my package.json file. (I saw this mentioned in the source and it appears
it doesn't work with the latest version which is 1.0.11 but it does work
with this version).

Greg Trihus

**Comment by CharlesStover** [comment]
I thought that might have been the case. The `use-force-update` dependency had an update that is not supported by all environments (I think mostly React Native?). The fix would be to change the version of that dependency.

Since it seems like you have found a fix for your project, and the pull request only affects dev dependencies (not the production bundle), I'll mark this as closed. Let me know if you need more assistance.

**Comment by gtryus** [comment]
yes, I am fine with that. I am not using react native but I could easily
imagine that others trying this library with the latest versions of the
create react app templates will have trouble too. I won't try to fix it for
you and you can fix it if you want.

Greg Trihus

**Pull request closed without merging**
