### PR TITLE
Updated addCallback documentation, plus minor formatting enhancements.

### PR DESCRIPTION
**Pull request by monteiz**
As discussed in #179, here is a pull request updating the addCallback documentation.

I took the chance to convert single quotes to double quotes and other minor formatting enhancements.

### CODE REVIEW

**Comment by CharlesStover** [comment]
The single quotes are a deliberate choice, though I don't mind the parenthesis around parameters (better matching TypeScript). :)

I don't think I'd want the quotes changed, since it is a different code style than all my other projects.

**Comment by monteiz** [comment]
So, I was somehow waiting for that, because it makes sense.

But I want to give you an input: since you use single quotes, I guess you do not use [prettier](https://prettier.io/). It comes as a plugin for the most popular IDE, and it does an amazing job. I use it with vscode, configured for automatically formatting the code on file save, so I am saving hundreds or even thousands CMD+F each day.

By default prettier format with double quotes. I think we should move to double quotes, since it is the standard for JSON, and JavaScript has template literals. This makes single quotes somehow obsolete in my view.

Prettier has formatted automatically also the `md` file, putting parenthesis around parameters. Cool, isn't it?

So, to me is very easy to change double quotes to single quotes, no problem (writing this comment took more time). But think about it one or two days, and let me know if you change your mind ;)

**Comment by monteiz** [comment]
Updated using with single quotes ;)

**Comment by CharlesStover** [comment]
I do use Prettier, and [my newer projects](https://github.com/CharlesStover/lazy-i18n/blob/master/.prettierrc.json#L11) have a Prettier config to enforce single quotes. Great tool. ReactN is such an old project, it was simply before I ever discovered Prettier. Any 3.x release of this project will have a prettier config as well as the other project configs [found here](https://github.com/CharlesStover/node-package-template).

At one point in time, single quotes had better performance than double; but I'm sure that has long-since been optimized out of existence by the engine. Today, I prefer single quotes, because it is less visual noise. Things like linters and Prettier for sure should be used to enforce these things, and the lack of it here is just evidence of the project's age. 😅

**Comment by monteiz** [comment]
> Any 3.x release of this project will have a prettier config as well as the other project configs found here.

Great choice!

> evidence of the project's age

This project is an _evergreen_, because it is still the best option out there for the global state management of a React application ;)

If needed, I will be happy to contribute further to documentation.

**Pull request merged**
